- name: grub2 config
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  become: true

- name: newaliases
  command: newaliases
  become: true

- name: plymouth rebuild initrd
  command: plymouth-set-default-theme {{ plymouth_theme }} --rebuild-initrd
  become: true

- name: Generate sasl_passwd.db from /etc/postfix/sasl_passwd
  command: postmap /etc/postfix/sasl_passwd
  become: true

- name: reload systemctl
  systemd:
    daemon_reload: yes
  become: true
