# keep-sorted start newline_separated=yes
cursor_extensions:
  # keep-sorted start
  - adamhartford.vscode-base64
  - antfu.slidev
  - bierner.markdown-mermaid
  - bierner.markdown-preview-github-styles
  - davidanson.vscode-markdownlint
  - esbenp.prettier-vscode
  - github.copilot
  - github.vscode-github-actions
  - github.vscode-pull-request-github
  - hashicorp.terraform
  - hverlin.mise-vscode
  - mechatroner.rainbow-csv
  - pkief.material-icon-theme
  - redhat.vscode-yaml
  - streetsidesoftware.code-spell-checker
  - tyriar.sort-lines
  - yzhang.markdown-all-in-one
  # keep-sorted end

# Directory where there are all the data (usually $HOME)
data_source_dir: "~"

email: petr.ruzicka@gmail.com

github_username: ruzickap

# The directories which should be copy over to new system
home_data_directories:
  # keep-sorted start
  - .bash_history
  - .gnupg
  - .sigstore
  - .ssh
  - .zsh_history
  - Desktop
  - Documents
  - Downloads
  - Movies
  - Music
  - Pictures
  - bin
  - git
  # keep-sorted end

krew_plugins:
  # keep-sorted start
  - cert-manager
  - get-all
  - ice
  - ktop
  - ns
  - resource-capacity
  - stern
  - view-allocations
  # keep-sorted end

my_hostname: peru.xvx.cz

postfix_form: petr.ruzicka@mylabs.dev

postfix_relayhost: live.smtp.mailtrap.io:2525

raspi_hostname: raspi.xvx.cz
# keep-sorted end
