my_hostname: peru.xvx.cz
email: petr.ruzicka@gmail.com

# Directory where there are all the data (usually $HOME)
data_source_dir: "~"

github_username: ruzickap

raspi_hostname: raspi.xvx.cz

# The directories which should be copy over to new system
home_data_directories:
  - .bash_history
  - .gnupg
  - .sigstore
  - .ssh
  - .zsh_history
  - bin
  - Desktop
  - Documents
  - Downloads
  - git
  - Movies
  - Music
  - Pictures

code_extensions:
  - adamhartford.vscode-base64
  - bierner.markdown-mermaid
  - bierner.markdown-preview-github-styles
  - DavidAnson.vscode-markdownlint
  - esbenp.prettier-vscode
  - GitHub.copilot
  - GitHub.copilot-chat
  - github.vscode-github-actions
  - golang.go
  - hashicorp.terraform
  - redhat.vscode-yamL
  - streetsidesoftware.code-spell-checker
  - Tyriar.sort-lines
  - yzhang.markdown-all-in-one

krew_plugins:
  - cert-manager
  - get-all
  - ice
  - ktop
  - ns
  - resource-capacity
  - stern
  - view-allocations
