# keep-sorted start newline_separated=yes
# Items to add to the dock
dock_add_items:
  - /Applications/iTerm.app
  - /Applications/Google Chrome.app

# The Dock icons size
dock_icons_size: 36.0

homebrew_casks:
  # keep-sorted start
  - alt-tab
  - brave-browser@beta
  - darktable
  - digikam
  - font-meslo-lg-nerd-font # Needed for iTerm2 + Oh My Zsh Theme
  - home-assistant
  - iterm2
  - keepassxc
  - keepingyouawake
  - kopiaui
  - mpv
  - mysides # Application for managing OS X Finder sidebar favorites
  - obs
  - stats
  - visual-studio-code
  # keep-sorted end

homebrew_packages:
  # keep-sorted start
  - ansible
  - atuin
  - awscli
  - bash
  - bat
  - checkov # needs gcc, openblas
  - cilium-cli
  - cloudflared # needed for ssh with cloudflare tunnels
  - colima
  - commitizen # git cz commands...
  - coreutils
  - dive
  - docker-buildx
  - dockutil
  - dua-cli
  - eks-node-viewer
  - eksctl
  - exiftool
  - findutils
  - fzf
  - g-ls # ls replacement
  - gawk
  - gh
  - git
  - git-delta # A viewer for git and diff output
  - gnu-sed
  - gnu-tar
  - gnupg
  - grep
  - helm
  - htop
  - imagemagick
  - iproute2mac
  - jq
  - k9s
  - keep-sorted
  - kind
  - kopia
  - krew
  - kubecolor
  - kubernetes-cli
  - markdownlint-cli
  - midnight-commander
  - mpg123 # needed for mc to display mp3 files
  - npm
  - opentofu
  - pre-commit
  - prettier
  - qpdf # needed for decrypt password protected PDFs
  - ratchet
  - rclone
  - rhash
  - rsync
  - shellcheck
  - shfmt
  - telnet
  - terraform
  - tflint
  - tfupdate
  - tig
  - trivy
  - watch
  - wget
  - wifi-password
  - yamllint
  - yq
  - yt-dlp
  - zoxide
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  # keep-sorted end

homebrew_prefix: "{% if (ansible_architecture | regex_search('arm')) %}/opt/homebrew/{% else %}/usr/local/{% endif %}"

homebrew_taps:
  - aws/tap

login_items_enabled:
  # keep-sorted start
  - AltTab
  - KeePassXC
  - Stats
  # keep-sorted end

login_picture_url: https://www.gravatar.com/avatar/{{ email | hash('md5') }}?s=500 # DevSkim: ignore DS126858

npm_packages:
  # keep-sorted start
  - "@slidev/cli"
  - "@slidev/theme-default"
  - mega-linter-runner
  # keep-sorted end

run_applications:
  - AltTab
  - Stats
# keep-sorted end
