login_picture_url: https://www.gravatar.com/avatar/{{ email | hash('md5') }}?s=500 # DevSkim: ignore DS126858

# Items to add to the dock
dock_add_items:
  - /Applications/iTerm.app
  - /Applications/Google Chrome.app

# The Dock icons size
dock_icons_size: 36.0

login_items_enabled:
  - AltTab
  - KeePassXC
  - Stats

homebrew_taps:
  - aws/tap

homebrew_prefix: "{% if (ansible_architecture | regex_search('arm')) %}/opt/homebrew/{% else %}/usr/local/{% endif %}"

homebrew_packages:
  - ansible
  - atuin
  - awscli
  - bash
  - bat
  - cdrtools # Needed for mc to show iso details
  # - checkov # needs gcc, openblas
  - cilium-cli
  - cloudflared # needed for ssh with cloudflare tunnels
  - colima
  - commitizen # git cz commands...
  - dive
  # - docker
  - docker-buildx
  - dockutil
  - dua-cli
  - coreutils
  - eks-node-viewer
  - eksctl
  - exiftool
  - findutils
  - fzf
  - g-ls # ls replacement
  - gawk
  - gh
  - git
  - git-delta # A viewer for git and diff output
  - gnu-sed
  - gnu-tar
  - gnupg
  - grep
  - helm
  - htop
  - imagemagick
  - iproute2mac
  - jless
  - jq
  - k9s
  - kind
  - kopia
  - krew
  - kubecolor
  - kubernetes-cli
  - markdownlint-cli
  - midnight-commander
  - mpg123 # needed for mc to display mp3 files
  - npm
  - opentofu
  - pre-commit
  - prettier
  - qpdf # needed for decrypt password protected PDFs
  - ratchet
  - rclone
  - rhash
  - rsync
  - shfmt
  - shellcheck
  - telnet
  - terraform
  - tflint
  - tfupdate
  - tig
  - trivy
  - watch
  - wget
  - wifi-password
  - yamllint
  - yt-dlp
  - yq
  - zoxide
  - zsh-autosuggestions
  - zsh-syntax-highlighting

homebrew_casks:
  - alt-tab
  - brave-browser@beta
  - darktable
  - digikam
  - font-meslo-lg-nerd-font # Needed for iTerm2 + Oh My Zsh Theme
  - home-assistant
  - iterm2
  - kopiaui
  - keepassxc
  - keepingyouawake
  - mpv
  - mysides # Application for managing OS X Finder sidebar favorites
  - obs
  - rectangle # Move and resize windows on macOS with keyboard shortcuts and snap areas
  - stats
  - vagrant
  - visual-studio-code
  - vmware-fusion
  - vagrant-vmware-utility

run_applications:
  - AltTab
  - Rectangle
  - Stats

npm_packages:
  - mega-linter-runner
  - "@slidev/cli"
  - "@slidev/theme-default"
