login_picture_url: https://www.gravatar.com/avatar/{{ email | hash('md5') }}?s=500

# Items to add to the dock
dock_add_items:
  - /Applications/iTerm.app
  - /Applications/Google Chrome.app

# The Dock icons size
dock_icons_size: 36.0

login_items_enabled:
  - AltTab
  - KeePassXC
  - Stats

homebrew_taps:
  - homebrew/cask-fonts
  - homebrew/cask-versions

homebrew_prefix: "{% if (ansible_architecture | regex_search('arm')) %}/opt/homebrew/{% else %}/usr/local/{% endif %}"

homebrew_packages:
  - ansible
  # - awscli # python@3.11
  - bash
  - bat
  - cdrtools # Needed for mc to show iso details
  # - checkov # needs gcc, openblas
  - colima
  - commitizen # git cz commands...
  - dive
  - docker
  - dockutil
  - dua-cli
  - coreutils
  - eksctl
  - eza
  - exiftool
  - findutils
  - fzf
  - gawk
  - gh
  - git
  - git-delta # A viewer for git and diff output
  - gnu-sed
  - gnu-tar
  - gnupg
  - grep
  - helm
  - htop
  - imagemagick
  - iproute2mac
  - jless
  - jq
  - kind
  - kopia
  - kops
  - krew
  - kubernetes-cli
  - markdownlint-cli
  - midnight-commander
  - mpg123 # needed for mc to display mp3 files
  - npm
  - opentofu
  - pre-commit
  - prettier
  - qpdf # needed for decrypt password protected PDFs
  - rclone
  - rhash
  - powerlevel10k
  - rsync
  - shellcheck
  - telnet
  - terraform
  - tflint
  - tfupdate
  - tig
  - trivy
  - watch
  - wget
  - wifi-password
  - yamllint
  - yt-dlp
  - yq
  - zoxide
  - zsh-autosuggestions
  - zsh-syntax-highlighting

homebrew_casks:
  - alt-tab
  - brave-browser-beta
  - darktable
  - digikam
  - font-meslo-lg-nerd-font # Needed for iTerm2 + powerlevel10k (Oh My Zsh Theme)
  - iterm2
  - keepassxc
  - mpv
  - mysides # Application for managing OS X Finder sidebar favorites
  - obs
  - rectangle # Move and resize windows on macOS with keyboard shortcuts and snap areas
  - stats
  - vagrant
  - visual-studio-code
  - vmware-fusion
  - vagrant-vmware-utility

run_applications:
  - AltTab
  - Rectangle
  - Stats

npm_packages:
  - mega-linter-runner
