name: fedora

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/fedora.yml
      - files/**
      - handlers/**
      - main.yml
      - tasks/Fedora.yml
      - tasks/common.yml
      - vars/Linux.yml
      - vars/common.yml
  push:
    branches:
      - master
    paths:
      - .github/workflows/fedora.yml
      - files/**
      - handlers/**
      - main.yml
      - tasks/Fedora.yml
      - tasks/common.yml
      - vars/Linux.yml
      - vars/common.yml

env:
  MYUSER: pruzicka
  PASSWORD: xxxx
  ANSIBLE_HOST_KEY_CHECKING: False
  ANSIBLE_REMOTE_PORT: 2222

jobs:
  fedora:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          brew install ansible gnu-sed hudochenkov/sshpass/sshpass

      - name: Stat Fedora VirtualBox VM
        env:
          RAM: 4096
        run: |
          vagrant init fedora/32-cloud-base
          gsed -i "/Vagrant.configure(\"2\") do |config|/a \ \ config.vm.provider \"virtualbox\" do |vb|\n \ \ \ \ vb.memory = \"${RAM}\"\n \ end" Vagrantfile
          vagrant up

      - name: Add main user to Fedora VirtualBox VM
        run: |
          echo "test password" > vault-my_workstation.password
          ansible --become --user vagrant --extra-vars "ansible_password=vagrant ansible_python_interpreter=/usr/bin/python3" -m user -a "name=${MYUSER} password={{ \"${PASSWORD}\" | password_hash('sha512') }} append=yes groups=wheel" -i "127.0.0.1," 127.0.0.1

      - name: Ansible
        run: |
          ansible-playbook --user="${MYUSER}" --skip-tags secrets,interactive,skip_test --extra-vars "ansible_password=${PASSWORD} ansible_become_password=${PASSWORD} ansible_python_interpreter=/usr/bin/python3" main.yml -i "127.0.0.1,"
