name: fedora

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/fedora.yml
      - files/**
      - handlers/**
      - main.yml
      - tasks/Fedora.yml
      - tasks/common.yml
      - vars/Linux.yml
      - vars/common.yml
  push:
    branches:
      - master
    paths:
      - .github/workflows/fedora.yml
      - files/**
      - handlers/**
      - main.yml
      - tasks/Fedora.yml
      - tasks/common.yml
      - vars/Linux.yml
      - vars/common.yml

env:
  MYUSER: pruzicka
  PASSWORD: xxxx
  ANSIBLE_HOST_KEY_CHECKING: False
  ANSIBLE_REMOTE_PORT: 2222
  RAM: 4096

jobs:
  fedora:
    runs-on: macos-latest
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v2

      - name: Update brew
        run: |
          brew update

      - name: Install brew packages
        run: |
          brew install ansible gnu-sed hudochenkov/sshpass/sshpass

      - name: Start Fedora VirtualBox VM
        run: |
          vagrant init fedora/33-cloud-base
          gsed -i "/Vagrant.configure(\"2\") do |config|/a \ \ config.vm.provider \"virtualbox\" do |vb|\n \ \ \ \ vb.memory = \"${RAM}\"\n \ end" Vagrantfile
          vagrant up || ( vagrant destroy --force && vagrant up )

      - name: Add main user to Fedora VirtualBox VM
        run: |
          echo "test password" > vault-my_workstation.password
          ansible --become --user vagrant --extra-vars "ansible_password=vagrant ansible_python_interpreter=/usr/bin/python3" -m user -a "name=${MYUSER} password={{ \"${PASSWORD}\" | password_hash('sha512') }} append=yes groups=wheel" -i "127.0.0.1," 127.0.0.1

      - name: Ansible
        run: |
          ansible-playbook --user="${MYUSER}" --skip-tags data,interactive,secrets,skip_test,test_data --extra-vars "ansible_password=${PASSWORD} ansible_become_password=${PASSWORD} ansible_python_interpreter=/usr/bin/python3" main.yml -i "127.0.0.1,"

      - name: Ansible - Idempotence tests
        run: |
          ansible-playbook --user="${MYUSER}" --skip-tags data,interactive,secrets,skip_test,test_data --extra-vars "ansible_password=${PASSWORD} ansible_become_password=${PASSWORD}" main.yml -i "127.0.0.1," | tee /tmp/ansible.log
          # https://stackoverflow.com/questions/59361798/github-actions-functions-on-the-console-output
          if [ $(grep 'changed=0.*failed=0' /tmp/ansible.log | wc -l) = 1 ] ; then
            echo -e '\nIdempotence test: pass'
            exit 0
          else
            echo -e '\nIdempotence test: fail\n'
            grep -B 2 '^changed:' /tmp/ansible.log
            exit 1
          fi
