name: macos

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/mac.yml
      - files/**
      - handlers/**
      - main.yml
      - tasks/MacOSX.yml
      - tasks/common.yml
      - vars/Darwin.yml
      - vars/common.yml
      - vars/secrets.yml.vault
  push:
    branches:
      - master
    paths:
      - .github/workflows/mac.yml
      - files/**
      - handlers/**
      - main.yml
      - tasks/MacOSX.yml
      - tasks/common.yml
      - vars/Darwin.yml
      - vars/common.yml
      - vars/secrets.yml.vault

jobs:
  macos-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Ansible packages
        run: |
          pip3 install --user ansible
          ln -s /Users/runner/Library/Python/3.7/bin/ansible /usr/local/bin/ansible
          ln -s /Users/runner/Library/Python/3.7/bin/ansible-playbook /usr/local/bin/ansible-playbook

      - name: Run Ansible
        run: |
          echo "test password" > vault-my_workstation.password
          ansible-playbook --skip-tags secrets,interactive,skip_test --connection=local -i "127.0.0.1," main.yml
