name: macos

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - tasks/MacOSX.yml
      - tasks/common.yml
      - .github/workflows/mac.yml
  push:
    branches:
      - master
    paths:
      - tasks/MacOSX.yml
      - tasks/common.yml
      - .github/workflows/mac.yml

jobs:
  macos-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Ansible packages
        run: |
          pip3 install --user ansible
          ln -s /Users/runner/Library/Python/3.7/bin/ansible /usr/local/bin/ansible
          ln -s /Users/runner/Library/Python/3.7/bin/ansible-playbook /usr/local/bin/ansible-playbook

      - name: Run Ansible
        run: |
          echo "test password" > vault-my_workstation.password
          ansible-playbook --diff --skip-tags secrets,interactive --connection=local -i "127.0.0.1," main.yml
