name: macos

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/macos.yml
      - ansible/files/**
      - ansible/handlers/**
      - ansible/main.yml
      - ansible/tasks/MacOSX.yml
      - ansible/tasks/common.yml
      - ansible/vars/Darwin.yml
      - ansible/vars/common.yml

env:
  ANSIBLE_DEBUG: False

jobs:
  macos:
    runs-on: macos-13
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          brew install ansible

      - name: Ansible
        run: |
          cd ansible || exit
          echo "test_password" > vault-my_workstation.password
          ansible-playbook --skip-tags data,interactive,secrets,skip_test --connection=local -i "127.0.0.1," main.yml

      - name: Ansible - Idempotence tests
        run: |
          cd ansible || exit
          ansible-playbook --skip-tags data,interactive,secrets,skip_test --connection=local -i "127.0.0.1," main.yml | tee /tmp/ansible.log
          # https://stackoverflow.com/questions/59361798/github-actions-functions-on-the-console-output
          if [ "$(grep -c 'changed=0.*failed=0' /tmp/ansible.log)" = "1" ] ; then
            echo -e '\n✅ Idempotence test: pass'
            exit 0
          else
            echo -e '\n❗️ Idempotence test: fail\n'
            grep -B 2 '^changed:' /tmp/ansible.log
            exit 1
          fi
