name: macos

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/macos.yml
      - files/**
      - handlers/**
      - main.yml
      - tasks/MacOSX.yml
      - tasks/common.yml
      - vars/Darwin.yml
      - vars/common.yml
  push:
    branches:
      - master
    paths:
      - .github/workflows/macos.yml
      - files/**
      - handlers/**
      - main.yml
      - tasks/MacOSX.yml
      - tasks/common.yml
      - vars/Darwin.yml
      - vars/common.yml

jobs:
  macos-test:
    runs-on: macos-latest
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          brew install ansible

      - name: Run Ansible
        run: |
          echo "test_password" > vault-my_workstation.password
          ansible-playbook --skip-tags secrets,interactive,skip_test,test_data -e 'ansible_python_interpreter=/usr/local/bin/python3' --connection=local -i "127.0.0.1," main.yml
